name: bond_app
description: A social meeting application focused on connecting users based on compatibility, shared interests, and real-time availability.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.3.5
  google_sign_in: ^6.1.5
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0
  
  # Routing
  go_router: ^10.2.0
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  google_fonts: ^4.0.4
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_dotenv: ^5.1.0
  
  # Location
  geolocator: ^10.1.1
  google_maps_flutter: ^2.5.3
  
  # Search
  algolia: ^1.1.2
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # NFC
  nfc_manager: ^3.3.0
  
  # Payment
  flutter_stripe: ^10.2.0
  
  # Network
  http: ^0.13.6
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Utilities
  uuid: ^3.0.7
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  url_launcher: ^6.1.14
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.2
  permission_handler: ^10.4.5
  convert: ^3.1.1
  sign_in_with_apple: ^6.1.4
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.4
  mockito: ^5.4.4
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - credentials/.env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
