// Mocks generated by Mockito 5.4.5 from annotations
// in fresh_bond_app/test/features/notifications/domain/blocs/notification_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fresh_bond_app/features/notifications/domain/models/notification_model.dart'
    as _i4;
import 'package:fresh_bond_app/features/notifications/domain/repositories/notification_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NotificationModel>> getAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, []),
            returnValue: _i3.Future<List<_i4.NotificationModel>>.value(
              <_i4.NotificationModel>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationModel>>);

  @override
  _i3.Future<List<_i4.NotificationModel>> getUnreadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotifications, []),
            returnValue: _i3.Future<List<_i4.NotificationModel>>.value(
              <_i4.NotificationModel>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationModel>>);

  @override
  _i3.Future<bool> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> subscribeToNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unsubscribeFromNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
