name: fresh_bond_app
description: A social meeting application focused on connecting users based on compatibility, shared interests, and real-time availability.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core UI and design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  
  # Networking and API
  dio: ^5.4.2
  internet_connection_checker: ^1.0.0+1
  
  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.3
  
  # Utilities
  logger: ^2.0.2+1
  intl: ^0.19.0
  uuid: ^4.3.3
  crypto: ^3.0.3
  
  # Testing utilities
  mockito: ^5.4.4
  
  # UI Widgets
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  
  # NFC
  nfc_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.5
  test: ^1.24.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/