// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the Bond app
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8J1Rxt-2MFhhbCGfaUYYpLk0qYoFkAHM',
    appId: '1:1015240617580:web:4a7c3e2c7d6f4b3c8d9e0f',
    messagingSenderId: '1015240617580',
    projectId: 'bond-dbc1d',
    authDomain: 'bond-dbc1d.firebaseapp.com',
    storageBucket: 'bond-dbc1d.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8J1Rxt-2MFhhbCGfaUYYpLk0qYoFkAHM',
    appId: '1:1015240617580:android:4a7c3e2c7d6f4b3c8d9e0f',
    messagingSenderId: '1015240617580',
    projectId: 'bond-dbc1d',
    storageBucket: 'bond-dbc1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8J1Rxt-2MFhhbCGfaUYYpLk0qYoFkAHM',
    appId: '1:1015240617580:ios:4a7c3e2c7d6f4b3c8d9e0f',
    messagingSenderId: '1015240617580',
    projectId: 'bond-dbc1d',
    storageBucket: 'bond-dbc1d.appspot.com',
    iosClientId: '1015240617580-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.example.bondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8J1Rxt-2MFhhbCGfaUYYpLk0qYoFkAHM',
    appId: '1:1015240617580:ios:4a7c3e2c7d6f4b3c8d9e0f',
    messagingSenderId: '1015240617580',
    projectId: 'bond-dbc1d',
    storageBucket: 'bond-dbc1d.appspot.com',
    iosClientId: '1015240617580-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.example.bondApp',
  );
}
